#DEFINE NALIGNBYTES 32

#DEFINE NI0(NI,NKIND) ( ( ((NI+1)*(NKIND) + NALIGNBYTES - 1 ) / NALIGNBYTES ) * NALIGNBYTES / (NKIND) - 1 )
#DEFINE NI1(NI,NKIND) ( ( ((NI  )*(NKIND) + NALIGNBYTES - 1 ) / NALIGNBYTES ) * NALIGNBYTES / (NKIND)     )
#DEFINE NI2(NI,NKIND) ( ( ((NI-1)*(NKIND) + NALIGNBYTES - 1 ) / NALIGNBYTES ) * NALIGNBYTES / (NKIND) + 1 )