#DEFINE NALIGNBYTES 32

#DEFINE SZPAD(SIZE,NKIND) ( ( ((SIZE)*(NKIND) + NALIGNBYTES - 1 ) / NALIGNBYTES ) * NALIGNBYTES / (NKIND) )

#DEFINE NI0(NKIND) ( ( ((NI+1)*(NKIND) + NALIGNBYTES - 1 ) / NALIGNBYTES ) * NALIGNBYTES / (NKIND) - 1 )
#DEFINE NI1(NKIND) ( ( ((NI  )*(NKIND) + NALIGNBYTES - 1 ) / NALIGNBYTES ) * NALIGNBYTES / (NKIND)     )
#DEFINE NI2(NKIND) ( ( ((NI-1)*(NKIND) + NALIGNBYTES - 1 ) / NALIGNBYTES ) * NALIGNBYTES / (NKIND) + 1 )
